language: java

arch:
    - amd64
    - arm64
cache:
  directories:
  - ~/.m2

git:
  depth: 3

branches:
  only:
    - master

install:
  - mvn clean package -B -U -e -Dmaven.test.skip

script: true
